# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(b'ADMIN', b'Access to all privileges'), (b'BASIC', b'Base user privileges')], default=b'ADMIN', max_length=5),
        ),
    ]
