# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170927_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(b'ADMIN', b'Access to all privileges'), (b'BASIC', b'Base user privileges')], default=b'BASIC', max_length=5),
        ),
    ]
