# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170928_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
